### Generated by rprotoc. DO NOT EDIT!
### <proto file: /Users/mikolaifajer/SkadiStats/spectre/aspectSerializer/src/main/proto/aspect/derived/vacuum.proto>
# package vacuum;
# 
# import "aspect/basic/player.proto"; // Get the TEAM enum
# 
# option java_package = "skadistats.spectre.proto.derived";
# 
# message GroupUpTime {
#     optional player.TEAM team  = 1;
#     optional double      time = 2;
# }
require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Vacuum
  require_relative '../basic/player.pb'
  ::Protobuf::OPTIONS[:"java_package"] = "skadistats.spectre.proto.derived"
  class GroupUpTime < ::Protobuf::Message
    defined_in __FILE__
    optional :'player::TEAM', :team, 1
    optional :double, :time, 2
  end
end
