### Generated by rprotoc. DO NOT EDIT!
### <proto file: /Users/mikolaifajer/SkadiStats/spectre/aspectSerializer/src/main/proto/aspect/basic/match.proto>
# package match;
# 
# import "aspect/basic/player.proto"; // Get the TEAM enum
# 
# option java_package = "skadistats.spectre.proto.basic";
# 
# message Draft {
#     optional int64 match_id = 1;
# 
#     message DraftEntry {
#         optional int32                 order    = 1;
#         optional int32                 hero_idx = 2;
#         optional player.TEAM           side     = 3;
#         optional bool                  is_pick  = 4;
#         optional int32                 duration = 5; // Duration in seconds for this pick/ban
#         optional player.PlayerIdentity player   = 6;
#     }
# 
#     repeated DraftEntry entries = 2;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Match
  require_relative './player.pb'
  ::Protobuf::OPTIONS[:"java_package"] = "skadistats.spectre.proto.basic"
  class Draft < ::Protobuf::Message
    defined_in __FILE__
    optional :int64, :match_id, 1
    class DraftEntry < ::Protobuf::Message
      defined_in __FILE__
      optional :int32, :order, 1
      optional :int32, :hero_idx, 2
      optional :'player::TEAM', :side, 3
      optional :bool, :is_pick, 4
      optional :int32, :duration, 5
      optional :'player::PlayerIdentity', :player, 6
    end
    repeated :DraftEntry, :entries, 2
  end
end
