### Generated by rprotoc. DO NOT EDIT!
### <proto file: /Users/mikolaifajer/SkadiStats/spectre/aspectSerializer/src/main/proto/aspect/basic/position.proto>
# package position;
# 
# option java_package = "skadistats.spectre.proto.basic";
# 
# message EntityPosition {
#     optional int32  entity_idx = 1;
#     optional sint32 pos_x      = 2;
#     optional sint32 pos_y      = 3;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Position
  ::Protobuf::OPTIONS[:"java_package"] = "skadistats.spectre.proto.basic"
  class EntityPosition < ::Protobuf::Message
    defined_in __FILE__
    optional :int32, :entity_idx, 1
    optional :sint32, :pos_x, 2
    optional :sint32, :pos_y, 3
  end
end