### Generated by rprotoc. DO NOT EDIT!
### <proto file: /Users/mikolaifajer/SkadiStats/spectre/aspectSerializer/src/main/proto/aspect/basic/life_state.proto>
# package life_state;
# 
# option java_package = "skadistats.spectre.proto.basic";
# 
# message EntityLifeState {
#     optional int32 entity_idx = 1;
#     optional bool  alive      = 2;
#     optional int32 current_hp = 3;
#     optional int32 max_hp     = 4;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module LifeState
  ::Protobuf::OPTIONS[:"java_package"] = "skadistats.spectre.proto.basic"
  class EntityLifeState < ::Protobuf::Message
    defined_in __FILE__
    optional :int32, :entity_idx, 1
    optional :bool, :alive, 2
    optional :int32, :current_hp, 3
    optional :int32, :max_hp, 4
  end
end