### Generated by rprotoc. DO NOT EDIT!
### <proto file: /Users/mikolaifajer/SkadiStats/spectre/aspectSerializer/src/main/proto/aspect/basic/player.proto>
# package player;
# 
# option java_package = "skadistats.spectre.proto.basic";
# 
# enum TEAM {
#      RADIANT = 0;
#      DIRE = 1;
#      SPECTATOR = 2;
#      OTHER = 4;
# }
# 
# message PlayerIdentity {
#     optional int64  player_id   = 3;
#     optional int32  hero_idx    = 1;
#     optional TEAM   team        = 2;
#     optional string player_name = 4;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Player
  ::Protobuf::OPTIONS[:"java_package"] = "skadistats.spectre.proto.basic"
  class TEAM < ::Protobuf::Enum
    defined_in __FILE__
    RADIANT = value(:RADIANT, 0)
    DIRE = value(:DIRE, 1)
    SPECTATOR = value(:SPECTATOR, 2)
    OTHER = value(:OTHER, 4)
  end
  class PlayerIdentity < ::Protobuf::Message
    defined_in __FILE__
    optional :int64, :player_id, 3
    optional :int32, :hero_idx, 1
    optional :TEAM, :team, 2
    optional :string, :player_name, 4
  end
end
